### ISSUE TITLE
"Look for new files" missing

### ISSUE THREAD

**Issue by Zauberfisch** [unclecheese/KickAssets#12]
in the normal silverstripe Files & Images tab you can find 3 buttons,  "Create", "Delete" and "Look for new files"Look for new files"

"SilverStripe maintains its own database of the files & images stored in your assets/ folder. Click this button to update that database, if files are added to the assets/ folder from outside SilverStripe, for example, if you have uploaded files via FTP."

for users uploading files via ftp this feature is required.

**Comment by dospuntocero** [comment]
totally agree with this point.

**Comment by Zauberfisch** [comment]
actually, I can close this issue.

I have already written a patch for that, its in [pull request #18](https://github.com/unclecheese/KickAssets/pull/18)

commits: 
[0838bd27395e14867d1453ee2e0bc656b588bb58](https://github.com/Zauberfisch/KickAssets/commit/0838bd27395e14867d1453ee2e0bc656b588bb58)
[99ca021a32da256034ed848fd7e1777949a20f77](https://github.com/Zauberfisch/KickAssets/commit/99ca021a32da256034ed848fd7e1777949a20f77)
