### ISSUE TITLE
When closing the "Browse files" dialog, FileAttachmentField shows "File doesn't exist"

### ISSUE THREAD

**Issue by bummzack** [unclecheese/KickAssets#2]
Steps to reproduce the bug:
- Use a FileAttachmentField in the CMS (to attach an image to a page)
- Click on "Browse files" to replace the current file with a new one
- Close the file browse window (using the close button on the top right)
- The FileAttachmentField will now show the text "File doesn't exist". The page in the CMS has to be refreshed to go back to the "normal" state.

**Comment by unclecheese** [comment]
I love detailed bug reports! Fixed!
