### ISSUE TITLE
Opening kick assets from a popup

### ISSUE THREAD

**Issue by MarcusDalgren** [unclecheese/KickAssets#6]
I'm currently using kick assets on a DataObject related to a page and the field itself works great. However trying to open the kick assets admin from there ends up looking really messy since the original popup window is already pretty small and kick assets admin needs to fit in the popup.

I'm not sure if there's a nice way around this but I just wanted to report it in. Everything else works great in the popup and I'm loving the drag&drop experience.

**Comment by unclecheese** [comment]
Yeah, I'm not intending for it to be used in DOM popups. Best to move that into ModelAdmin.

**Comment by unclecheese** [comment]
Ultimately, I'd like to move DOM to a model that does not use popups, but with DataGrid on the way, I think I'll just wait. KickAssets is designed to conform to the SS 3.0 specs, and to bake in functionality for components that will be deprecated, such as DOM, doesn't make a whole lot of sense to me.

**Comment by MarcusDalgren** [comment]
Is there any way we could turn off the option of actually opening the kick assets UI from a popup so we could still use the field but stop users from trying to open the big UI? Since the rest works and it's a nice experience and all.

**Comment by unclecheese** [comment]
Added disableExistingFileSelection() function.
